# Create ArgoCD namespace for EKS Cluster
resource "kubernetes_namespace" "argocd" {
  metadata {
    name = var.argocd_namespace
    labels = {
      "app.kubernetes.io/name" = "argocd"
      "cluster-type"           = "eks"
    }
  }
}

# Install ArgoCD using Helm
resource "helm_release" "argocd" {
  name             = "argocd"
  repository       = "https://argoproj.github.io/argo-helm"
  chart            = "argo-cd"
  namespace        = kubernetes_namespace.argocd.metadata[0].name
  version          = var.argocd_chart_version
  create_namespace = false
  wait             = true
  wait_for_jobs    = true

  values = [
    yamlencode({
      global = {
        domain = var.argocd_domain
      }

      server = {
        service = {
          type = var.enable_ingress ? "ClusterIP" : "LoadBalancer"
          # When not using ingress, annotate the Classic ELB to terminate SSL.
          # This allows the browser to connect over HTTPS while ArgoCD serves plain HTTP.
          annotations = !var.enable_ingress && var.acm_certificate_arn != "" ? {
            "service.beta.kubernetes.io/aws-load-balancer-ssl-cert"         = var.acm_certificate_arn
            "service.beta.kubernetes.io/aws-load-balancer-ssl-ports"        = "443"
            "service.beta.kubernetes.io/aws-load-balancer-backend-protocol" = "http"
          } : {}
        }

        ingress = {
          enabled          = var.enable_ingress
          ingressClassName = "traefik"
          annotations = var.enable_ingress ? {
            # Route via the HTTPS entrypoint and enable TLS
            "traefik.ingress.kubernetes.io/router.entrypoints" = "websecure"
            "traefik.ingress.kubernetes.io/router.tls"         = "true"
            # Enable gRPC (used by ArgoCD CLI / UI)
            "traefik.ingress.kubernetes.io/router.middlewares" = ""
          } : {}
          hosts = var.enable_ingress ? [var.argocd_domain] : []
          tls = var.enable_ingress ? [{
            secretName = "argocd-tls"
            hosts      = [var.argocd_domain]
          }] : []
        }
      }

      configs = {
        # Authentication enabled with auto-generated admin password
        params = {
          # Set server.insecure=true when TLS is terminated externally (ELB, ingress controller).
          # Keeps ArgoCD serving plain HTTP and avoids TLS-on-TLS or HTTP/2 ALPN issues.
          "server.insecure"     = var.server_insecure
          "server.disable.auth" = false
        }
        # Password will be auto-generated by ArgoCD
      }

      controller = {
        replicas = 1
      }

      repoServer = {
        replicas = 1
      }

      applicationSet = {
        replicas = 1
      }

      redis = {
        enabled = true
      }

      dex = {
        enabled = true
      }

      notifications = {
        enabled = false
      }
    })
  ]

  depends_on = [kubernetes_namespace.argocd]
}

# Create initial ArgoCD Application for GitOps
# Note: The Application resource is managed separately after ArgoCD is deployed
# This is because the CRD may not be available during terraform plan
# Instead, create applications using kubectl or a separate Terraform apply
#
# Example to create an Application after ArgoCD is deployed:
# kubectl apply -f - <<EOF
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: root-app
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: <git_repository_url>
#     targetRevision: <git_repository_branch>
#     path: <git_repository_path>
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - CreateNamespace=true
# EOF
